src/Entity/Chantier.php
<?php

namespace App\Entity;

use App\Repository\ChantierRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ChantierRepository::class)
 */
class Chantier
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="date")
     */
    private $dateDebut;

    /**
     * @ORM\OneToMany(targetEntity=Pointage::class, mappedBy="chantier", orphanRemoval=true)
     */
    private $pointages;

    /**
     * Chantier constructor.
     */
    public function __construct()
    {
        $this->pointages = new ArrayCollection();
    }

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string|null
     */
    public function getNom(): ?string
    {
        return $this->nom;
    }

    /**
     * @param string $nom
     * @return $this
     */
    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    /**
     * @param string $adresse
     * @return $this
     */
    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    /**
     * @return \DateTimeInterface|null
     */
    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->dateDebut;
    }

    /**
     * @param \DateTimeInterface $dateDebut
     * @return $this
     */
    public function setDateDebut(\DateTimeInterface $dateDebut): self
    {
        $this->dateDebut = $dateDebut;

        return $this;
    }

    /**
     * @return Collection|Pointage[]
     */
    public function getPointages(): Collection
    {
        return $this->pointages;
    }

    /**
     * @param Pointage $pointage
     * @return $this
     */
    public function addPointage(Pointage $pointage): self
    {
        if (!$this->pointages->contains($pointage)) {
            $this->pointages[] = $pointage;
            $pointage->setChantier($this);
        }

        return $this;
    }

    /**
     * @param Pointage $pointage
     * @return $this
     */
    public function removePointage(Pointage $pointage): self
    {
        if ($this->pointages->removeElement($pointage)) {
            // set the owning side to null (unless already changed)
            if ($pointage->getChantier() === $this) {
                $pointage->setChantier(null);
            }
        }

        return $this;
    }
    public function getTotalHeures(): int
    {
        $total = 0;
        foreach ($this->pointages as $pointage)
        {
            $total += $pointage->getDuree();
        }
        return $total;
    }
}

src/Entity/Utilisateur.php
<?php

namespace App\Entity;

use App\Repository\PointageRepository;
use App\Repository\UtilisateurRepository;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Exception;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=UtilisateurRepository::class)
 * @ORM\Table(name="`user`")
 * @UniqueEntity("matricule")
 */
class Utilisateur
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=25)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=25)
     */
    private $prenom;


    /**
     * @ORM\Column(type="string", length=10)
     */
    private $matricule;

    /**
     * @ORM\OneToMany(targetEntity=Pointage::class, mappedBy="utilisateur", orphanRemoval=true)
     */
    private $pointages;

    /**
     * Utilisateur constructor.
     */
    public function __construct()
    {
        $this->pointages = new ArrayCollection();
    }


    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string|null
     */
    public function getNom(): ?string
    {
        return $this->nom;
    }

    /**
     * @param string $nom
     * @return $this
     */
    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    /**
     * @param string $prenom
     * @return $this
     */
    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getMatricule(): ?string
    {
        return $this->matricule;
    }

    /**
     * @param string $matricule
     * @return $this
     */
    public function setMatricule(string $matricule): self
    {
        $this->matricule = $matricule;

        return $this;
    }

    /**
     * @return Collection|Pointage[]
     */
    public function getPointages(): Collection
    {
        return $this->pointages;
    }

    /**
     * @return Pointage|false
     */
    public function getDernierPointage()
    {
        if ($this->pointages->count())
            return array_reverse($this->pointages->toArray())[0];
        return false;
    }

    /**
     * @param string $date
     * @return Collection|Pointage[]
     * @throws Exception
     */
    public function getPointagesSemaine(string $date)
    {
        $criteria = PointageRepository::semaineCriteria($date);
        return $this->pointages->matching($criteria);
    }

    /**
     * @param DateTimeInterface $date
     * @return Collection|Pointage[]
     */
    public function getPointagesJour(DateTimeInterface $date)
    {
        $criteria = PointageRepository::jourCriteria($date);
        return $this->pointages->matching($criteria);
    }

    /**
     * @param Pointage $pointage
     * @return $this
     */
    public function addPointage(Pointage $pointage): self
    {
        if (!$this->pointages->contains($pointage)) {
            $this->pointages[] = $pointage;
            $pointage->setUtilisateur($this);
        }

        return $this;
    }

    /**
     * @param Pointage $pointage
     * @return $this
     */
    public function removePointage(Pointage $pointage): self
    {
        if ($this->pointages->removeElement($pointage)) {
            // set the owning side to null (unless already changed)
            if ($pointage->getUtilisateur() === $this) {
                $pointage->setUtilisateur(null);
            }
        }

        return $this;
    }

    /**
     * @return string
     */
    public function getNomComplet()
    {
        return mb_strtoupper($this->nom) . ' ' . $this->prenom;
    }
}

src/Form/ChantierType.php
<?php

namespace App\Form;

use App\Entity\Chantier;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ChantierType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom',TextType::class,[
                'required' => true,
            ])
            ->add('adresse',TextType::class,[
                'required' => true,
            ])
            ->add('dateDebut',DateType::class,[
                'widget' => 'single_text',
                'format' => 'dd/MM/yyyy',
                'label'=> 'Début de chantier (DD/MM/YYYY)'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Chantier::class,
        ]);
    }
}

src/Controller/ChantierController.php
<?php

namespace App\Controller;

use App\Entity\Chantier;
use App\Form\ChantierType;
use App\Repository\ChantierRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/chantier")
 */
class ChantierController extends AbstractController
{
    /**
     * @Route("/", name="chantier_index", methods={"GET"})
     * @param ChantierRepository $chantierRepository
     * @return Response
     */
    public function index(ChantierRepository $chantierRepository): Response
    {
        return $this->render('chantier/index.html.twig', [
            'chantiers' => $chantierRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="chantier_new", methods={"GET","POST"})
     * @param Request $request
     * @return Response
     */
    public function new(Request $request): Response
    {
        $chantier = new Chantier();
        $form = $this->createForm(ChantierType::class, $chantier);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($chantier);
            $entityManager->flush();

            return $this->redirectToRoute('chantier_index');
        }

        return $this->render('chantier/new.html.twig', [
            'chantier' => $chantier,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="chantier_show", methods={"GET"})
     * @param Chantier $chantier
     * @return Response
     */
    public function show(Chantier $chantier): Response
    {
        return $this->render('chantier/show.html.twig', [
            'chantier' => $chantier,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="chantier_edit", methods={"GET","POST"})
     * @param Request $request
     * @param Chantier $chantier
     * @return Response
     */
    public function edit(Request $request, Chantier $chantier): Response
    {
        $form = $this->createForm(ChantierType::class, $chantier);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('chantier_index');
        }

        return $this->render('chantier/edit.html.twig', [
            'chantier' => $chantier,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="chantier_delete", methods={"DELETE"})
     * @param Request $request
     * @param Chantier $chantier
     * @return Response
     */
    public function delete(Request $request, Chantier $chantier): Response
    {
        if ($this->isCsrfTokenValid('delete'.$chantier->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($chantier);
            $entityManager->flush();
        }

        return $this->redirectToRoute('chantier_index');
    }
}

templates/chantier/_delete_form.html.twig
<form method="post" action="{{ path('chantier_delete', {'id': chantier.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ chantier.id) }}">
    <button class="btn btn-danger"><i class="fas fa-times"></i></button>
</form>

templates/chantier/_form.html.twig
{{ form_start(form, {'attr': {'id': 'form_chantier'}}) }}
    {{ form_widget(form) }}
{{ form_end(form) }}

templates/chantier/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Chantier{% endblock %}

{% block body %}
    <section class="p-3 p-md-5">
        <h1><i class="fas fa-edit"></i> {{ chantier.nom }}<span
                    class="text-danger">.</span></h1>
        <div class="rounded overflow-hidden shadow-lg bg-white px-3 pb-1">
            <div class="py-3">{{ include('chantier/_form.html.twig') }}</div>
            <footer class="row bg-light p-3 rounded">
                <div class="col">
                    <a href="{{ path('chantier_index') }}" class="btn btn-dark"><i class="fas fa-backward"></i></a>
                </div>
                <div class="col text-end">
                    <button class="btn btn-success" form="form_chantier" type="submit"><i class="fas fa-check"></i>
                        Enregistrer les modifications
                    </button>
                </div>
            </footer>
        </div>
    </section>
{% endblock %}

templates/chantier/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Chantier index{% endblock %}

{% block body %}
    <section class="p-3 p-md-5">
        <div class="row align-items-center">
            <h1 class="col"><i class="fas fa-hard-hat"></i> Chantiers<span class="text-danger">.</span></h1>
            <div class="col text-end">
                <button class="btn btn-dark" data-href="{{ path('chantier_new') }}"><i class="fas fa-hard-hat"></i> Nouveau chantier</button>
                {% include 'nav.html.twig' %}
            </div>
        </div>
        <div class="rounded overflow-hidden shadow-lg bg-white">
            <table class="w-100 table table-borderless text-center table-hover mb-0">
                <thead class="bg-light">
                <tr>
                    <th>#</th>
                    <th>Nom</th>
                    <th>Adresse</th>
                    <th>Début de chantier</th>
                    <th>Total heures</th>
                    <th class="text-end">Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for chantier in chantiers %}
                    <tr >
                        <td class="align-middle">
                            <figure class="m-0">
                                <img src="https://via.placeholder.com/50" alt="Id chantier" class="rounded-circle">
                            </figure>
                        </td>
                        <td class="align-middle">{{ chantier.nom }}</td>
                        <td class="align-middle">{{ chantier.adresse }}</td>
                        <td class="align-middle">{{ chantier.dateDebut ? chantier.dateDebut|date('d.m.Y') : '' }}</td>
                        <td class="align-middle"><span class="badge bg-info"><i class="fas fa-clock"></i> {{ chantier.totalHeures }} heure(s)</span></td>
                        <td class="text-end align-middle">
                            <a href="{{ path('chantier_show', {'id': chantier.id}) }}" class="btn btn-secondary"><i class="fas fa-eye"></i></a>
                            <a href="{{ path('chantier_edit', {'id': chantier.id}) }}" class="btn btn-dark"><i class="fas fa-edit"></i></a>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="6">Aucun chantier</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </section>

{% endblock %}

templates/chantier/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Chantier{% endblock %}

{% block body %}
    <section class="p-3 p-md-5">
        <h1><i class="fas fa-hard-hat"></i> Nouveau chantier<span
                    class="text-danger">.</span></h1>
        <div class="rounded overflow-hidden shadow-lg bg-white px-3 pb-1">
            <div class="py-3">{{ include('chantier/_form.html.twig') }}</div>
    <footer class="row bg-light p-3 rounded">
        <div class="col">
            <a href="{{ path('chantier_index') }}" class="btn btn-dark"><i class="fas fa-backward"></i></a>
        </div>
        <div class="col text-end">
            <button class="btn btn-success" form="form_chantier" type="submit"><i class="fas fa-check"></i>
                Créer le chantier
            </button>
        </div>
    </footer>
    </div>
    </section>
{% endblock %}

templates/chantier/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Chantier{% endblock %}

{% block body %}
<section class="p-3 p-md-5">
    <h1><i class="fas fa-eye"></i> {{ chantier.nom }}<span class="text-danger">.</span></h1>
    <div class="rounded overflow-hidden shadow-lg bg-white px-3 py-1">
        <table class="table table-borderless">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ chantier.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ chantier.nom }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ chantier.adresse }}</td>
            </tr>
            <tr>
                <th>DateDebut</th>
                <td>{{ chantier.dateDebut ? chantier.dateDebut|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Pointages <br>
                <span class="badge bg-info"><i class="fas fa-clock"></i> {{ chantier.totalHeures }} heure(s)</span></th>
                <td>{% for pointage in chantier.pointages %}
                        <span class="badge bg-info"><i class="fas fa-calendar"></i> {{ pointage.date|date('d.m.Y') }}</span>
                        <span class="badge bg-secondary"><i class="fas fa-clock"></i> {{ pointage.duree|number_format(2) }}</span>
                        <span class="badge bg-dark text-white"><a href="{{ path('utilisateur_show',{id:pointage.utilisateur.id}) }}" class="text-decoration-none text-white"><i class="fas fa-user"></i> {{ pointage.utilisateur.nomComplet }}</a></span>
                        <br>
                    {% else %}
                        <em><i class="fas fa-times"></i> Aucun pointage connu</em>
                    {% endfor %}</td>
            </tr>
        </tbody>
    </table>
        <footer class="row bg-light p-3 rounded">
            <div class="col">
                <a href="{{ path('chantier_index') }}" class="btn btn-dark"><i class="fas fa-backward"></i></a>
            </div>
            <div class="col text-center">
                <a href="{{ path('chantier_edit', {'id': chantier.id}) }}" class="btn btn-warning"><i class="fas fa-edit"></i></a>
            </div>
            <div class="text-end col">{{ include('chantier/_delete_form.html.twig') }}</div>
        </footer>
    </div>
</section>
{% endblock %}