src/Entity/Utilisateur.php
<?php

namespace App\Entity;

use App\Repository\PointageRepository;
use App\Repository\UtilisateurRepository;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Exception;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=UtilisateurRepository::class)
 * @ORM\Table(name="`user`")
 * @UniqueEntity("matricule")
 */
class Utilisateur
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=25)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=25)
     */
    private $prenom;


    /**
     * @ORM\Column(type="string", length=10)
     */
    private $matricule;

    /**
     * @ORM\OneToMany(targetEntity=Pointage::class, mappedBy="utilisateur", orphanRemoval=true)
     */
    private $pointages;

    /**
     * Utilisateur constructor.
     */
    public function __construct()
    {
        $this->pointages = new ArrayCollection();
    }


    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string|null
     */
    public function getNom(): ?string
    {
        return $this->nom;
    }

    /**
     * @param string $nom
     * @return $this
     */
    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    /**
     * @param string $prenom
     * @return $this
     */
    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getMatricule(): ?string
    {
        return $this->matricule;
    }

    /**
     * @param string $matricule
     * @return $this
     */
    public function setMatricule(string $matricule): self
    {
        $this->matricule = $matricule;

        return $this;
    }

    /**
     * @return Collection|Pointage[]
     */
    public function getPointages(): Collection
    {
        return $this->pointages;
    }

    /**
     * @return Pointage|false
     */
    public function getDernierPointage()
    {
        if ($this->pointages->count())
            return array_reverse($this->pointages->toArray())[0];
        return false;
    }

    /**
     * @param string $date
     * @return Collection|Pointage[]
     * @throws Exception
     */
    public function getPointagesSemaine(string $date)
    {
        $criteria = PointageRepository::semaineCriteria($date);
        return $this->pointages->matching($criteria);
    }

    /**
     * @param DateTimeInterface $date
     * @return Collection|Pointage[]
     */
    public function getPointagesJour(DateTimeInterface $date)
    {
        $criteria = PointageRepository::jourCriteria($date);
        return $this->pointages->matching($criteria);
    }

    /**
     * @param Pointage $pointage
     * @return $this
     */
    public function addPointage(Pointage $pointage): self
    {
        if (!$this->pointages->contains($pointage)) {
            $this->pointages[] = $pointage;
            $pointage->setUtilisateur($this);
        }

        return $this;
    }

    /**
     * @param Pointage $pointage
     * @return $this
     */
    public function removePointage(Pointage $pointage): self
    {
        if ($this->pointages->removeElement($pointage)) {
            // set the owning side to null (unless already changed)
            if ($pointage->getUtilisateur() === $this) {
                $pointage->setUtilisateur(null);
            }
        }

        return $this;
    }

    /**
     * @return string
     */
    public function getNomComplet()
    {
        return mb_strtoupper($this->nom) . ' ' . $this->prenom;
    }
}

src/Form/UtilisateurType.php
<?php

namespace App\Form;

use App\Entity\Utilisateur;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UtilisateurType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom',TextType::class,[
                "required" => true,
            ])
            ->add('prenom',TextType::class,[
                "required" => true,
            ])
            ->add('matricule',TextType::class,[
                "required" => true,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Utilisateur::class,
        ]);
    }
}

src/Controller/UtilisateurController.php
<?php

namespace App\Controller;

use App\Entity\Utilisateur;
use App\Form\UtilisateurType;
use App\Repository\UtilisateurRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/utilisateur")
 */
class UtilisateurController extends AbstractController
{
    /**
     * @Route("/", name="utilisateur_index", methods={"GET"})
     * @param UtilisateurRepository $utilisateurRepository
     * @return Response
     */
    public function index(UtilisateurRepository $utilisateurRepository): Response
    {
        return $this->render('utilisateur/index.html.twig', [
            'utilisateurs' => $utilisateurRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="utilisateur_new", methods={"GET","POST"})
     * @param Request $request
     * @return Response
     */
    public function new(Request $request): Response
    {
        $utilisateur = new Utilisateur();
        $form = $this->createForm(UtilisateurType::class, $utilisateur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($utilisateur);
            $entityManager->flush();

            return $this->redirectToRoute('utilisateur_index');
        }

        return $this->render('utilisateur/new.html.twig', [
            'utilisateur' => $utilisateur,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="utilisateur_show", methods={"GET"})
     * @param Utilisateur $utilisateur
     * @return Response
     */
    public function show(Utilisateur $utilisateur): Response
    {

        return $this->render('utilisateur/show.html.twig', [
            'utilisateur' => $utilisateur,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="utilisateur_edit", methods={"GET","POST"})
     * @param Request $request
     * @param Utilisateur $utilisateur
     * @return Response
     */
    public function edit(Request $request, Utilisateur $utilisateur): Response
    {
        $form = $this->createForm(UtilisateurType::class, $utilisateur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('utilisateur_index');
        }

        return $this->render('utilisateur/edit.html.twig', [
            'utilisateur' => $utilisateur,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="utilisateur_delete", methods={"DELETE"})
     * @param Request $request
     * @param Utilisateur $utilisateur
     * @return Response
     */
    public function delete(Request $request, Utilisateur $utilisateur): Response
    {
        if ($this->isCsrfTokenValid('delete'.$utilisateur->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($utilisateur);
            $entityManager->flush();
        }

        return $this->redirectToRoute('utilisateur_index');
    }
}

templates/utilisateur/_delete_form.html.twig
<form method="post" action="{{ path('utilisateur_delete', {'id': utilisateur.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ utilisateur.id) }}">
    <button class="btn btn-danger"><i class="fas fa-times"></i></button>
</form>

templates/utilisateur/_form.html.twig
{{ form_start(form, {'attr': {'id': 'form_utilisateur'}}) }}
    {{ form_widget(form) }}

{{ form_end(form) }}

templates/utilisateur/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Utilisateur{% endblock %}

{% block body %}
    <section class="p-3 p-md-5">
        <h1><i class="fas fa-edit"></i> {{ utilisateur.nom|upper ~' '~ utilisateur.prenom|capitalize }}<span
                    class="text-danger">.</span></h1>
        <div class="rounded overflow-hidden shadow-lg bg-white px-3 pb-1">
            <div class="py-3">{{ include('utilisateur/_form.html.twig') }}</div>
            <footer class="row bg-light p-3 rounded">
                <div class="col">
                    <a href="{{ path('utilisateur_index') }}" class="btn btn-dark"><i class="fas fa-backward"></i></a>
                </div>
                <div class="col text-end">
                    <button class="btn btn-success" form="form_utilisateur" type="submit"><i class="fas fa-check"></i>
                        Enregistrer les modifications
                    </button>
                </div>
            </footer>
        </div>
    </section>
{% endblock %}

templates/utilisateur/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Utilisateur index{% endblock %}

{% block body %}
    <section class="p-3 p-md-5">
        <div class="row align-items-center">
            <h1 class="col"><i class="fas fa-users"></i> Utilisateurs<span class="text-danger">.</span></h1>
            <div class="col text-end">
                <button class="btn btn-dark" data-href="{{ path('utilisateur_new') }}"><i class="fas fa-user-plus"></i> Nouvel utilisateur</button>
                {% include 'nav.html.twig' %}
            </div>
        </div>
        <div class="rounded overflow-hidden shadow-lg bg-white">
            <table class="w-100 table table-borderless text-center table-hover mb-0">
                <thead class="bg-light">
                <tr>
                    <th>#</th>
                    <th>Nom</th>
                    <th>Prenom</th>
                    <th>Matricule</th>
                    <th>Dernier pointage</th>
                    <th class="text-end">Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for utilisateur in utilisateurs %}
                    <tr class="bg-white">
                        <td class="align-middle">
                            <figure class="m-0">
                                <img src="https://via.placeholder.com/50" alt="Id user" class="rounded-circle">
                            </figure>
                        </td>
                        <td class="align-middle">{{ utilisateur.nom }}</td>
                        <td class="align-middle">{{ utilisateur.prenom }}</td>
                        <td class="align-middle">{{ utilisateur.matricule }}</td>
                        <td class="align-middle">
                            {% if utilisateur.dernierPointage %}
                                <span class="badge bg-info"><i class="fas fa-calendar"></i> {{ utilisateur.dernierPointage.date|date('d.m.Y') }}</span>
                                <span class="badge bg-secondary"><i class="fas fa-clock"></i> {{ utilisateur.dernierPointage.duree|number_format(2) }}</span>
                                <span class="badge bg-dark text-white"><a href="{{ path('chantier_show',{id:utilisateur.dernierPointage.chantier.id}) }}" class="text-decoration-none text-white"><i class="fas fa-hard-hat"></i> {{ utilisateur.nomComplet }}</a></span>

                            {% else %}
                                <em><i class="fas fa-times"></i> Aucun pointage connu</em>
                            {% endif %}
                        </td>
                        <td class="align-middle text-end">
                            <a href="{{ path('utilisateur_show', {'id': utilisateur.id}) }}" class="btn btn-secondary"><i class="fas fa-eye"></i></a>
                            <a href="{{ path('utilisateur_edit', {'id': utilisateur.id}) }}" class="btn btn-dark"><i class="fas fa-edit"></i></a>
                        </td>
                    </tr>
                {% else %}
                    <tr class="bg-white">
                        <td colspan="6" class="align-middle">Aucun utilisateur</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </section>
{% endblock %}

templates/utilisateur/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Utilisateur{% endblock %}

{% block body %}
    <section class="p-3 p-md-5">
        <h1><i class="fas fa-user-plus"></i> Nouvel utilisateur<span
                    class="text-danger">.</span></h1>
        <div class="rounded overflow-hidden shadow-lg bg-white px-3 pb-1">
            <div class="py-3">{{ include('utilisateur/_form.html.twig') }}</div>
            <footer class="row bg-light p-3 rounded">
                <div class="col">
                    <a href="{{ path('utilisateur_index') }}" class="btn btn-dark"><i class="fas fa-backward"></i></a>
                </div>
                <div class="col text-end">
                    <button class="btn btn-success" form="form_utilisateur" type="submit"><i class="fas fa-check"></i>
                        Créer l'utilisateur
                    </button>
                </div>
            </footer>
        </div>
    </section>
{% endblock %}

templates/utilisateur/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Utilisateur{% endblock %}

{% block body %}
    <section class="p-3 p-md-5">
        <h1><i class="fas fa-eye"></i> {{ utilisateur.nom|upper ~' '~ utilisateur.prenom|capitalize }}<span
                    class="text-danger">.</span></h1>
        <div class="rounded overflow-hidden shadow-lg bg-white px-3 py-1">
            <table class="table table-borderless">
                <tbody>
                <tr>
                    <th>Id</th>
                    <td>{{ utilisateur.id }}</td>
                </tr>
                <tr>
                    <th>Nom</th>
                    <td>{{ utilisateur.nom }}</td>
                </tr>
                <tr>
                    <th>Prenom</th>
                    <td>{{ utilisateur.prenom }}</td>
                </tr>
                <tr>
                    <th>Matricule</th>
                    <td>{{ utilisateur.matricule }}</td>
                </tr>
                <tr>
                    <th>Pointages</th>
                    <td>{% for pointage in utilisateur.pointages %}
                            <span class="badge bg-info"><i class="fas fa-calendar"></i> {{ pointage.date|date('d.m.Y') }}</span>
                            <span class="badge bg-secondary"><i class="fas fa-clock"></i> {{ pointage.duree|number_format(2) }}</span>
                            <span class="badge bg-dark text-white"><a href="{{ path('chantier_show',{id:pointage.chantier.id}) }}" class="text-decoration-none text-white"><i class="fas fa-hard-hat"></i> {{ pointage.chantier.nom }}</a></span>
                            <br>
                        {% else %}
                            <em><i class="fas fa-times"></i> Aucun pointage connu</em>
                        {% endfor %}</td>
                </tr>
                </tbody>
            </table>

            <footer class="row bg-light p-3 rounded">
                <div class="col">
                    <a href="{{ path('utilisateur_index') }}" class="btn btn-dark"><i class="fas fa-backward"></i></a>
                </div>
                <div class="col text-center">
                    <a href="{{ path('utilisateur_edit', {'id': utilisateur.id}) }}" class="btn btn-warning"><i
                                class="fas fa-edit"></i></a>
                </div>
                <div class="text-end col">{{ include('utilisateur/_delete_form.html.twig') }}</div>
            </footer>
        </div>
    </section>
{% endblock %}